    .gba
    
    ADDR_KEY equ 0x02001EB0
    ADDR_GAMESTATE equ 0x02030B61
    
    VAL_KEY_A equ 0x1
    VAL_KEY_B equ 0x2
    VAL_KEY_SEL equ 0x4
    VAL_KEY_START equ 0x8
    VAL_KEY_RIGHT equ 0x10
    VAL_KEY_LEFT equ 0x20
    VAL_KEY_UP equ 0x40
    VAL_KEY_DOWN equ 0x80
    VAL_KEY_R equ 0x100
    VAL_KEY_L equ 0x200
    VAL_STAGE_INTRO equ 0x1
    VAL_STAGE_FLIZARD equ 0x2
    VAL_STAGE_CHILDRE equ 0x3
    VAL_STAGE_HELLBAT equ 0x4
    VAL_STAGE_MANTISK equ 0x5
    VAL_STAGE_BABY1 equ 0x6
    VAL_STAGE_ANUBIS equ 0x7
    VAL_STAGE_HANUMACHINE equ 0x8
    VAL_STAGE_BLIZZACK equ 0x9
    VAL_STAGE_COPYX equ 0xA
    VAL_STAGE_FOXTAR equ 0xB
    VAL_STAGE_CACTANK equ 0xC
    VAL_STAGE_VOLTEEL equ 0xD
    VAL_STAGE_KELVERIAN equ 0xE
    VAL_STAGE_BABY2 equ 0xF
    VAL_STAGE_FINAL equ 0x10
    VAL_STAGE_COMMANDERROOM equ 0x11
    
    OFFSET_KEY_A equ 0
    OFFSET_KEY_B equ 1
    OFFSET_KEY_SEL equ 2
    OFFSET_KEY_START equ 3
    OFFSET_KEY_RIGHT equ 4
    OFFSET_KEY_LEFT equ 5
    OFFSET_KEY_UP equ 6
    OFFSET_KEY_DOWN equ 7
    OFFSET_KEY_R equ 8
    OFFSET_KEY_L equ 9